# Generated by Django 5.2.6 on 2025-11-30 20:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def _table_exists(schema_editor, table_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        introspection = schema_editor.connection.introspection
        if hasattr(introspection, "table_names"):
            table_names = introspection.table_names(cursor)
        else:
            table_names = [table.name for table in introspection.get_table_list(cursor)]
    return table_name in table_names


def _column_exists(schema_editor, table_name: str, column_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        try:
            description = schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        except Exception:
            return False
    columns = {getattr(column, "name", column[0]) for column in description}
    return column_name in columns


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class CreateModelIfNotExists(migrations.CreateModel):
    """CreateModel that skips if the table already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        if _table_exists(schema_editor, table_name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddFieldIfNotExists(migrations.AddField):
    """AddField that skips if column already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)
        table_name = model._meta.db_table
        column_name = field.column
        if _column_exists(schema_editor, table_name, column_name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0054_merge_20251130_1949"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name="BoardGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "progressed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="progress"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        CreateModelIfNotExists(
            name="HistoricalBoardGame",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical board game",
                "verbose_name_plural": "historical board games",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        RemoveConstraintIfExists(
            model_name="item",
            name="app_item_media_type_valid",
        ),
        RemoveConstraintIfExists(
            model_name="item",
            name="app_item_source_valid",
        ),
        migrations.AlterField(
            model_name="item",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Board Game"),
                ],
                default="movie",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        AddConstraintIfNotExists(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source__in",
                        [
                            "tmdb",
                            "mal",
                            "mangaupdates",
                            "igdb",
                            "openlibrary",
                            "hardcover",
                            "comicvine",
                            "bgg",
                            "manual",
                        ],
                    )
                ),
                name="app_item_source_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "media_type__in",
                        [
                            "tv",
                            "season",
                            "episode",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                        ],
                    )
                ),
                name="app_item_media_type_valid",
            ),
        ),
        AddFieldIfNotExists(
            model_name="boardgame",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.item"
            ),
        ),
        AddFieldIfNotExists(
            model_name="boardgame",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalboardgame",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
