# Generated by Django 5.2.8 on 2025-12-04 15:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0055_boardgame_historicalboardgame_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "musicbrainz_release_id",
                    models.CharField(
                        blank=True,
                        help_text="MusicBrainz Release ID (UUID)",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("image", models.URLField(blank=True, default="")),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sort_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "musicbrainz_id",
                    models.CharField(
                        blank=True,
                        help_text="MusicBrainz Artist ID (UUID)",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                ("image", models.URLField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMusic",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical music",
                "verbose_name_plural": "historical musics",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "progressed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="progress"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="app_item_source_valid",
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="app_item_media_type_valid",
        ),
        migrations.AlterField(
            model_name="item",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                ],
                default="movie",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source__in",
                        [
                            "tmdb",
                            "mal",
                            "mangaupdates",
                            "igdb",
                            "openlibrary",
                            "hardcover",
                            "comicvine",
                            "bgg",
                            "musicbrainz",
                            "manual",
                        ],
                    )
                ),
                name="app_item_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "media_type__in",
                        [
                            "tv",
                            "season",
                            "episode",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "music",
                        ],
                    )
                ),
                name="app_item_media_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="artist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("musicbrainz_id__isnull", False)),
                fields=("musicbrainz_id",),
                name="unique_artist_musicbrainz_id",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="app.artist",
            ),
        ),
        migrations.AddField(
            model_name="historicalmusic",
            name="album",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="app.album",
            ),
        ),
        migrations.AddField(
            model_name="historicalmusic",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Convenience FK to artist (can be derived via album)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="app.artist",
            ),
        ),
        migrations.AddField(
            model_name="historicalmusic",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="music",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracks",
                to="app.album",
            ),
        ),
        migrations.AddField(
            model_name="music",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                help_text="Convenience FK to artist (can be derived via album)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracks",
                to="app.artist",
            ),
        ),
        migrations.AddField(
            model_name="music",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.item"
            ),
        ),
        migrations.AddField(
            model_name="music",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                condition=models.Q(("musicbrainz_release_id__isnull", False)),
                fields=("musicbrainz_release_id",),
                name="unique_album_musicbrainz_release_id",
            ),
        ),
    ]
