# Generated by Django 5.2.8 on 2025-12-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0056_add_music_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="tracks_populated",
            field=models.BooleanField(
                default=False,
                help_text="Whether tracks have been fetched from MusicBrainz",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="albums_populated",
            field=models.BooleanField(
                default=False,
                help_text="Whether albums have been fetched from MusicBrainz",
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="music_entries",
                to="app.album",
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                help_text="Convenience FK to artist (can be derived via album)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="music_entries",
                to="app.artist",
            ),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "musicbrainz_recording_id",
                    models.CharField(
                        blank=True,
                        help_text="MusicBrainz Recording ID (UUID)",
                        max_length=36,
                        null=True,
                    ),
                ),
                ("track_number", models.PositiveIntegerField(blank=True, null=True)),
                ("disc_number", models.PositiveIntegerField(default=1)),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in milliseconds", null=True
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracklist",
                        to="app.album",
                    ),
                ),
            ],
            options={
                "ordering": ["disc_number", "track_number", "title"],
            },
        ),
        migrations.AddField(
            model_name="historicalmusic",
            name="track",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Link to Track catalog entry from MusicBrainz",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="app.track",
            ),
        ),
        migrations.AddField(
            model_name="music",
            name="track",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to Track catalog entry from MusicBrainz",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="music_entries",
                to="app.track",
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                condition=models.Q(("track_number__isnull", False)),
                fields=("album", "disc_number", "track_number"),
                name="unique_track_per_album_disc",
            ),
        ),
    ]
