# Generated by Django 5.2.12 on 2026-04-05 17:30

from django.db import migrations
from simple_history.utils import bulk_create_with_history, bulk_update_with_history

from app.models import MediaTypes, Status


def reopen_completed_tv_with_new_seasons(apps, _):
    """Backfill completed TV entries when discovered seasons already exist."""
    from django.apps import apps # https://stackoverflow.com/questions/62418465/why-does-djangos-apps-get-model-return-a-fake-mymodel-object

    Item = apps.get_model("app", "Item")
    Season = apps.get_model("app", "Season")
    TV = apps.get_model("app", "TV")

    completed_tvs = TV.objects.filter(
        status=Status.COMPLETED.value,
        item__media_type=MediaTypes.TV.value,
    ).select_related("item", "user")

    for tv in completed_tvs.iterator():
        existing_seasons = Season.objects.filter(
            related_tv=tv,
        )

        if existing_seasons.exclude(status=Status.COMPLETED.value).exists():
            continue

        existing_season_numbers = set(
            existing_seasons.values_list("item__season_number", flat=True),
        )

        missing_season_items = list(
            Item.objects.filter(
                media_id=tv.item.media_id,
                source=tv.item.source,
                media_type=MediaTypes.SEASON.value,
                season_number__gt=0,
                event__isnull=False,
            )
            .exclude(season_number__in=existing_season_numbers)
            .distinct()
            .order_by("season_number")
        )

        if not missing_season_items:
            continue

        seasons_to_create = [
            Season(
                item=season_item,
                related_tv=tv,
                user=tv.user,
                status=Status.PLANNING.value,
            )
            for season_item in missing_season_items
        ]
        bulk_create_with_history(
            seasons_to_create,
            Season,
            default_user=tv.user,
        )

        tv.status = Status.IN_PROGRESS.value
        bulk_update_with_history(
            [tv],
            TV,
            ["status"],
            default_user=tv.user,
        )


class Migration(migrations.Migration):
    """Backfill reopened TV shows when discovered seasons already exist."""

    dependencies = [
        ("events", "0014_delete_empty_content_number_comic_events"),
        ("app", "0056_alter_item_media_id"),
    ]

    operations = [
        migrations.RunPython(
            reopen_completed_tv_with_new_seasons,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
