# Generated by Django 5.2.8 on 2025-12-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0057_add_track_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ["-release_date", "title"]},
        ),
        migrations.RemoveConstraint(
            model_name="album",
            name="unique_album_musicbrainz_release_id",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="albums_populated",
        ),
        migrations.AddField(
            model_name="album",
            name="musicbrainz_release_group_id",
            field=models.CharField(
                blank=True,
                help_text="MusicBrainz Release Group ID (UUID) - groups multiple releases",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="release_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Album type: Album, EP, Single, Compilation, etc.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="discography_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the discography was last synced from MusicBrainz",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="musicbrainz_release_id",
            field=models.CharField(
                blank=True,
                help_text="MusicBrainz Release ID (UUID) - one specific release",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                condition=models.Q(("musicbrainz_release_group_id__isnull", False)),
                fields=("artist", "musicbrainz_release_group_id"),
                name="unique_album_per_artist_release_group",
            ),
        ),
    ]
