# Generated by Django 5.2.8 on 2025-12-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0061_add_album_tracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="genres",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Genres/tags from MusicBrainz release",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="country",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO country code from MusicBrainz",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="genres",
            field=models.JSONField(
                blank=True, default=list, help_text="Top genres/tags from MusicBrainz"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="genres",
            field=models.JSONField(
                blank=True, default=list, help_text="Genres/tags for this recording"
            ),
        ),
    ]
