# Generated by Django 5.2.8 on 2025-12-14 15:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0062_album_genres_artist_country_artist_genres_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPodcast",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "played_up_to_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Last seen playedUpTo in seconds from API",
                        null=True,
                    ),
                ),
                (
                    "last_seen_status",
                    models.IntegerField(
                        blank=True,
                        help_text="Last seen playingStatus from API (2=in-progress, 3=completed)",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical podcast",
                "verbose_name_plural": "historical podcasts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "progressed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="progress"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "played_up_to_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Last seen playedUpTo in seconds from API",
                        null=True,
                    ),
                ),
                (
                    "last_seen_status",
                    models.IntegerField(
                        blank=True,
                        help_text="Last seen playingStatus from API (2=in-progress, 3=completed)",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_uuid",
                    models.CharField(
                        help_text="Pocket Casts episode UUID",
                        max_length=36,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.CharField(blank=True, default="", max_length=255)),
                ("published", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("audio_url", models.URLField(blank=True, default="")),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                ("season_number", models.PositiveIntegerField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, default="", max_length=50)),
                (
                    "episode_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Podcast Episode",
                "verbose_name_plural": "Podcast Episodes",
                "ordering": ["-published", "episode_number"],
            },
        ),
        migrations.CreateModel(
            name="PodcastShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "podcast_uuid",
                    models.CharField(
                        help_text="Pocket Casts podcast UUID",
                        max_length=36,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.CharField(blank=True, default="", max_length=255)),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                ("image", models.URLField(blank=True, default="")),
                ("language", models.CharField(blank=True, default="", max_length=10)),
                ("genres", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Podcast Show",
                "verbose_name_plural": "Podcast Shows",
                "ordering": ["title"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="app_item_source_valid",
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="app_item_media_type_valid",
        ),
        migrations.AlterField(
            model_name="item",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                ],
                default="movie",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source__in",
                        [
                            "tmdb",
                            "mal",
                            "mangaupdates",
                            "igdb",
                            "openlibrary",
                            "hardcover",
                            "comicvine",
                            "bgg",
                            "musicbrainz",
                            "pocketcasts",
                            "manual",
                        ],
                    )
                ),
                name="app_item_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "media_type__in",
                        [
                            "tv",
                            "season",
                            "episode",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    )
                ),
                name="app_item_media_type_valid",
            ),
        ),
        migrations.AddField(
            model_name="historicalpodcast",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.item"
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_entries",
                to="app.podcastepisode",
            ),
        ),
        migrations.AddField(
            model_name="historicalpodcast",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="app.podcastepisode",
            ),
        ),
        migrations.AddField(
            model_name="podcastepisode",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="app.podcastshow",
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="show",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_entries",
                to="app.podcastshow",
            ),
        ),
        migrations.AddField(
            model_name="historicalpodcast",
            name="show",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="app.podcastshow",
            ),
        ),
    ]
