# Generated by Django 5.2.8 on 2025-12-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0064_add_podcast_show_tracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcastshow",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Show description from Pocket Casts"
            ),
        ),
    ]
