# Generated by Django 5.2.8 on 2025-12-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0065_add_podcast_show_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcastshow",
            name="rss_feed_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="RSS feed URL for fetching full episode list",
            ),
        ),
    ]
