# Generated by Django 5.2.8 on 2025-12-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0066_add_rss_feed_url_to_podcast_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
