# Generated by Django 5.2.8 on 2025-12-31 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0067_item_genres"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataBackfillState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[("runtime", "Runtime"), ("genres", "Genres")],
                        max_length=20,
                    ),
                ),
                ("fail_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("give_up", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_backfill_states",
                        to="app.item",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "field"),
                        name="unique_metadata_backfill_state",
                    ),
                ],
                "indexes": [
                    models.Index(fields=["field", "next_retry_at"], name="app_metadat_field_31c9d9_idx"),
                    models.Index(fields=["field", "give_up"], name="app_metadat_field_6f2a2d_idx"),
                ],
            },
        ),
    ]
