# Generated by Django 5.2.9 on 2026-01-11 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0068_metadata_backfill_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="metadatabackfillstate",
            new_name="app_metadat_field_b78eb9_idx",
            old_name="app_metadat_field_31c9d9_idx",
        ),
        migrations.RenameIndex(
            model_name="metadatabackfillstate",
            new_name="app_metadat_field_a25091_idx",
            old_name="app_metadat_field_6f2a2d_idx",
        ),
    ]
