# Generated by Django 5.2.9 on 2026-01-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0069_rename_app_metadat_field_31c9d9_idx_app_metadat_field_b78eb9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="number_of_pages",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of pages for books", null=True
            ),
        ),
    ]
