# Generated by Django 5.2.9 on 2026-01-23 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0070_add_number_of_pages_to_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the item was added to collection",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the collection entry was last updated",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Physical/digital source: bluray, dvd, digital, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Resolution: 720p, 1080p, 4k, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "hdr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HDR format: HDR10, Dolby Vision, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "is_3d",
                    models.BooleanField(
                        default=False, help_text="Whether the media is 3D"
                    ),
                ),
                (
                    "audio_codec",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Audio codec: AAC, DTS, TrueHD, Atmos, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "audio_channels",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Audio channels: 2.0, 5.1, 7.1.2, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-collected_at"],
                        name="app_collect_user_id_79b4ed_idx",
                    ),
                    models.Index(
                        fields=["user", "item"], name="app_collect_user_id_e7c8c8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"), name="unique_user_collection_item"
                    )
                ],
            },
        ),
    ]
