# Generated by Django 5.2.9 on 2026-01-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0071_add_collection_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionentry",
            name="bitrate",
            field=models.IntegerField(
                blank=True,
                help_text="Audio bitrate in kbps (e.g., 128, 320, 1411)",
                null=True,
            ),
        ),
    ]
