# Generated by Django 5.2.9 on 2026-01-26 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0072_add_bitrate_to_collection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionentry",
            name="plex_rating_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Cached Plex rating key for this item (populated from webhook events)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collectionentry",
            name="plex_rating_key_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Plex rating key was last updated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collectionentry",
            name="plex_uri",
            field=models.CharField(
                blank=True,
                help_text="Cached Plex server URI for this item",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentry",
            index=models.Index(
                fields=["user", "plex_rating_key"],
                name="app_collect_user_id_5c40a5_idx",
            ),
        ),
    ]
