# Generated by Django 5.2.9 on 2026-01-27 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0053_add_boardgame"),
        ("app", "0073_add_plex_rating_key_cache"),
    ]

    operations = []
