# Generated by Django 5.2.9 on 2026-01-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0074_merge_20260127_1754"),
    ]

    operations = [
        # Alter fields first - this updates the model definition
        migrations.AlterField(
            model_name="item",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                ],
                default="movie",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        # Remove old constraints - SQLite will recreate the table
        # We'll handle constraint validation by ensuring data is valid first
        migrations.RemoveConstraint(
            model_name="item",
            name="app_item_source_valid",
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="app_item_media_type_valid",
        ),
        # Add new constraints with updated values
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source__in",
                        [
                            "tmdb",
                            "mal",
                            "mangaupdates",
                            "igdb",
                            "openlibrary",
                            "hardcover",
                            "comicvine",
                            "bgg",
                            "musicbrainz",
                            "pocketcasts",
                            "manual",
                        ],
                    )
                ),
                name="app_item_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "media_type__in",
                        [
                            "tv",
                            "season",
                            "episode",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    )
                ),
                name="app_item_media_type_valid",
            ),
        ),
    ]
