# Generated by Django 5.2.9 on 2026-02-06 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0075_remove_item_app_item_source_valid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("igdb", "Internet Game Database"),
                            ("openlibrary", "Open Library"),
                            ("hardcover", "Hardcover"),
                            ("comicvine", "Comic Vine"),
                            ("bgg", "BoardGameGeek"),
                            ("musicbrainz", "MusicBrainz"),
                            ("pocketcasts", "Pocket Casts"),
                            ("manual", "Manual"),
                        ],
                        default="tmdb",
                        max_length=20,
                    ),
                ),
                ("source_person_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("image", models.URLField(blank=True, default="")),
                (
                    "known_for_department",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("biography", models.TextField(blank=True, default="")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("female", "Female"),
                            ("male", "Male"),
                            ("non_binary", "Non-binary"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["source", "source_person_id"],
                        name="app_person_source_fe985d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_person_id"),
                        name="app_person_unique_source_person",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("igdb", "Internet Game Database"),
                            ("openlibrary", "Open Library"),
                            ("hardcover", "Hardcover"),
                            ("comicvine", "Comic Vine"),
                            ("bgg", "BoardGameGeek"),
                            ("musicbrainz", "MusicBrainz"),
                            ("pocketcasts", "Pocket Casts"),
                            ("manual", "Manual"),
                        ],
                        default="tmdb",
                        max_length=20,
                    ),
                ),
                ("source_studio_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("logo", models.URLField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["source", "source_studio_id"],
                        name="app_studio_source_b4f644_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_studio_id"),
                        name="app_studio_unique_source_studio",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemPersonCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[("cast", "Cast"), ("crew", "Crew")], max_length=10
                    ),
                ),
                ("role", models.CharField(blank=True, default="", max_length=255)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("sort_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_credits",
                        to="app.item",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_credits",
                        to="app.person",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "person__name"],
                "indexes": [
                    models.Index(
                        fields=["item", "role_type"],
                        name="app_itemper_item_id_6b2128_idx",
                    ),
                    models.Index(
                        fields=["person", "role_type"],
                        name="app_itemper_person__d7e863_idx",
                    ),
                    models.Index(
                        fields=["department"], name="app_itemper_departm_520226_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "person", "role_type", "role", "department"),
                        name="app_itempersoncredit_unique_credit",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemStudioCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studio_credits",
                        to="app.item",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_credits",
                        to="app.studio",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "studio__name"],
                "indexes": [
                    models.Index(
                        fields=["item"], name="app_itemstu_item_id_b82688_idx"
                    ),
                    models.Index(
                        fields=["studio"], name="app_itemstu_studio__a9f499_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "studio"),
                        name="app_itemstudiocredit_unique_item_studio",
                    )
                ],
            },
        ),
    ]
