# Generated by Django 5.2.9 on 2026-02-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0076_person_studio_itempersoncredit_itemstudiocredit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatabackfillstate",
            name="field",
            field=models.CharField(
                choices=[
                    ("runtime", "Runtime"),
                    ("genres", "Genres"),
                    ("credits", "Credits"),
                ],
                max_length=20,
            ),
        ),
    ]
