# Generated by Django 5.2.9 on 2026-02-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0080_metadatabackfillstate_strategy_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="series_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="series_position",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
