# Generated by Django 5.2.9 on 2026-02-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0081_item_series_name_item_series_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="authors",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of authors"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="country",
            field=models.CharField(
                blank=True, default="", help_text="Origin country", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="creators",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of creators (Comics)"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="format",
            field=models.CharField(
                blank=True, default="", help_text="Media format type", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="isbn",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of ISBN numbers"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="languages",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of languages"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="platforms",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of platforms (Games)"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="publishers",
            field=models.CharField(
                blank=True, default="", help_text="Publisher name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="runtime",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Formatted runtime string",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="source_material",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Source material (Anime)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                blank=True, default="", help_text="Production status", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="studios",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of production studios"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="themes",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of themes (Games)"
            ),
        ),
    ]
