# Generated by Django 5.2.9 on 2026-02-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0082_add_metadata_fields_to_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="metadata_fetched_at",
            field=models.DateTimeField(
                blank=True, help_text="When metadata was last fetched", null=True
            ),
        ),
    ]
