# Generated by Django 5.2.9 on 2026-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0083_add_metadata_fetched_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="localized_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="original_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
