# Generated by Django 5.2.9 on 2026-02-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0084_item_localized_title_item_original_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionentry",
            name="resolution",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resolution: 720p, 1080p, 4k, etc.",
                max_length=100,
            ),
        ),
    ]
