# Generated by Django 5.2.9 on 2026-02-14 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0085_alter_collectionentry_resolution"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collectionentry",
            name="unique_user_collection_item",
        ),
    ]
