# Generated by Django 5.2.9 on 2026-02-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0086_remove_unique_collection_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatabackfillstate",
            name="field",
            field=models.CharField(
                choices=[
                    ("runtime", "Runtime"),
                    ("genres", "Genres"),
                    ("credits", "Credits"),
                    ("release", "Release Date"),
                ],
                max_length=20,
            ),
        ),
    ]
