# Generated by Django 5.2.9 on 2026-02-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0091_fix_movie_progress"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="item",
            name="app_item_source_valid",
        ),
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                default="tmdb",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                default="tmdb",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source__in",
                        [
                            "tmdb",
                            "mal",
                            "mangaupdates",
                            "igdb",
                            "openlibrary",
                            "hardcover",
                            "comicvine",
                            "bgg",
                            "musicbrainz",
                            "pocketcasts",
                            "audiobookshelf",
                            "manual",
                        ],
                    )
                ),
                name="app_item_source_valid",
            ),
        ),
    ]
