# Generated by Django 5.2.9 on 2026-02-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0092_remove_item_app_item_source_valid_alter_item_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempersoncredit",
            name="role_type",
            field=models.CharField(
                choices=[("cast", "Cast"), ("crew", "Crew"), ("author", "Author")],
                max_length=10,
            ),
        ),
    ]
