# Generated by Django 5.2.9 on 2026-03-03 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0094_tag_itemtag_tag_app_tag_user_id_b053bd_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="provider_popularity",
            field=models.FloatField(
                blank=True,
                help_text="Normalized popularity value from provider metadata",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="provider_rating",
            field=models.FloatField(
                blank=True,
                help_text="Average rating value from provider metadata",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="provider_rating_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Rating count from provider metadata", null=True
            ),
        ),
        migrations.CreateModel(
            name="DiscoverApiCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("endpoint", models.CharField(max_length=255)),
                ("params_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "endpoint"],
                        name="app_discove_provide_e5556e_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="app_discove_expires_eb96f5_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "endpoint", "params_hash"),
                        name="discover_api_cache_unique_endpoint_params",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiscoverRowCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_type", models.CharField(default="all", max_length=20)),
                ("row_key", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("built_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discover_row_caches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id", "media_type", "row_key"],
                "indexes": [
                    models.Index(
                        fields=["user", "media_type"],
                        name="app_discove_user_id_c16919_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="app_discove_expires_9ede30_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "media_type", "row_key"),
                        name="discover_row_cache_unique_user_media_row",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiscoverTasteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_type", models.CharField(default="all", max_length=20)),
                ("genre_affinity", models.JSONField(blank=True, default=dict)),
                ("recent_genre_affinity", models.JSONField(blank=True, default=dict)),
                ("tag_affinity", models.JSONField(blank=True, default=dict)),
                ("person_affinity", models.JSONField(blank=True, default=dict)),
                ("activity_snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discover_taste_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id", "media_type"],
                "indexes": [
                    models.Index(
                        fields=["user", "media_type"],
                        name="app_discove_user_id_7ed49b_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="app_discove_expires_1e16cc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "media_type"),
                        name="discover_taste_profile_unique_user_media_type",
                    )
                ],
            },
        ),
    ]
