# Generated by Django 5.2.9 on 2026-03-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0095_item_provider_popularity_item_provider_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_genre_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_tag_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="recent_tag_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
