# Generated by Django 5.2.9 on 2026-03-06 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0096_discovertasteprofile_phase_genre_affinity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discovertasteprofile",
            name="negative_genre_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="negative_person_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="negative_tag_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="DiscoverFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[("not_interested", "Not interested")],
                        default="not_interested",
                        max_length=32,
                    ),
                ),
                ("source_context", models.CharField(default="discover", max_length=32)),
                ("row_key", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discover_feedback",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discover_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id", "feedback_type", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "feedback_type", "updated_at"],
                        name="app_discove_user_id_2f7886_idx",
                    ),
                    models.Index(
                        fields=["item"], name="app_discove_item_id_43dff1_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item", "feedback_type"),
                        name="discover_feedback_unique_user_item_feedback_type",
                    )
                ],
            },
        ),
    ]
