# Generated by Django 5.2.9 on 2026-03-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0097_discovertasteprofile_negative_genre_affinity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovertasteprofile",
            name="certification_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="collection_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="decade_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="director_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="keyword_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="lead_cast_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_certification_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_collection_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_decade_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_director_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_keyword_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_lead_cast_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_runtime_bucket_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="phase_studio_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="recent_certification_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="recent_collection_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="recent_decade_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="recent_director_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="recent_keyword_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="recent_lead_cast_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="recent_runtime_bucket_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="recent_studio_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="runtime_bucket_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="studio_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="item",
            name="provider_certification",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Primary provider certification/content rating",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="provider_collection_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Provider collection/franchise id",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="provider_collection_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Provider collection/franchise name",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="provider_keywords",
            field=models.JSONField(
                blank=True, default=list, help_text="Provider keywords"
            ),
        ),
    ]
