# Generated by Django 5.2.9 on 2026-03-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0098_discovertasteprofile_certification_affinity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatabackfillstate",
            name="field",
            field=models.CharField(
                choices=[
                    ("runtime", "Runtime"),
                    ("genres", "Genres"),
                    ("credits", "Credits"),
                    ("release", "Release Date"),
                    ("discover", "Discover Metadata"),
                ],
                max_length=20,
            ),
        ),
    ]
