# Generated by Django 5.2.9 on 2026-03-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0099_alter_metadatabackfillstate_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovertasteprofile",
            name="comfort_library_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="comfort_rewatch_affinity",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
