# Generated by Django 5.2.9 on 2026-03-19 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_library_media_types(apps, schema_editor):
    """Populate library_media_type for existing items."""
    del schema_editor
    Item = apps.get_model("app", "Item")

    for media_type in [
        "tv",
        "season",
        "episode",
        "anime",
        "movie",
        "manga",
        "game",
        "book",
        "comic",
        "boardgame",
        "music",
        "podcast",
    ]:
        Item.objects.filter(
            media_type=media_type,
            library_media_type="",
        ).update(library_media_type=media_type)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0101_item_provider_game_lengths_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemProviderLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("tvdb", "TheTVDB"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("igdb", "Internet Game Database"),
                            ("openlibrary", "Open Library"),
                            ("hardcover", "Hardcover"),
                            ("comicvine", "Comic Vine"),
                            ("bgg", "BoardGameGeek"),
                            ("musicbrainz", "MusicBrainz"),
                            ("pocketcasts", "Pocket Casts"),
                            ("audiobookshelf", "Audiobookshelf"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_media_id", models.CharField(max_length=32)),
                (
                    "provider_media_type",
                    models.CharField(
                        choices=[
                            ("tv", "TV Show"),
                            ("season", "TV Season"),
                            ("episode", "Episode"),
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                            ("game", "Game"),
                            ("book", "Book"),
                            ("comic", "Comic"),
                            ("boardgame", "Board Game"),
                            ("music", "Music"),
                            ("podcast", "Podcast"),
                        ],
                        max_length=10,
                    ),
                ),
                ("season_number", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_offset", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "provider",
                    "provider_media_type",
                    "provider_media_id",
                    "season_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="MetadataProviderPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("tvdb", "TheTVDB"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("igdb", "Internet Game Database"),
                            ("openlibrary", "Open Library"),
                            ("hardcover", "Hardcover"),
                            ("comicvine", "Comic Vine"),
                            ("bgg", "BoardGameGeek"),
                            ("musicbrainz", "MusicBrainz"),
                            ("pocketcasts", "Pocket Casts"),
                            ("audiobookshelf", "Audiobookshelf"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="app_item_source_valid",
        ),
        migrations.AddField(
            model_name="anime",
            name="migrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="anime",
            name="migrated_to_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="migrated_anime_entries",
                to="app.item",
            ),
        ),
        migrations.AddField(
            model_name="historicalanime",
            name="migrated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalanime",
            name="migrated_to_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="app.item",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="library_media_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                ],
                default="",
                help_text="Library bucket for this item (e.g. grouped anime stored on TV rows).",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            backfill_library_media_types,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                default="tmdb",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                default="tmdb",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source__in",
                        [
                            "tmdb",
                            "tvdb",
                            "mal",
                            "mangaupdates",
                            "igdb",
                            "openlibrary",
                            "hardcover",
                            "comicvine",
                            "bgg",
                            "musicbrainz",
                            "pocketcasts",
                            "audiobookshelf",
                            "manual",
                        ],
                    )
                ),
                name="app_item_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("library_media_type", ""),
                    (
                        "library_media_type__in",
                        [
                            "tv",
                            "season",
                            "episode",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    ),
                    _connector="OR",
                ),
                name="app_item_library_media_type_valid",
            ),
        ),
        migrations.AddField(
            model_name="itemproviderlink",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_links",
                to="app.item",
            ),
        ),
        migrations.AddField(
            model_name="metadataproviderpreference",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_provider_preferences",
                to="app.item",
            ),
        ),
        migrations.AddField(
            model_name="metadataproviderpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_provider_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="itemproviderlink",
            index=models.Index(
                fields=["provider", "provider_media_type", "provider_media_id"],
                name="app_itempro_provide_7e9ce4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemproviderlink",
            index=models.Index(
                fields=["item", "provider"], name="app_itempro_item_id_4fc1f0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemproviderlink",
            constraint=models.UniqueConstraint(
                fields=("item", "provider", "provider_media_type", "season_number"),
                name="app_itemproviderlink_unique_item_provider_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemproviderlink",
            constraint=models.UniqueConstraint(
                fields=(
                    "provider",
                    "provider_media_type",
                    "provider_media_id",
                    "season_number",
                ),
                name="app_itemproviderlink_unique_provider_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="metadataproviderpreference",
            index=models.Index(
                fields=["user", "provider"], name="app_metadat_user_id_105f02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadataproviderpreference",
            index=models.Index(
                fields=["item", "provider"], name="app_metadat_item_id_20816f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="metadataproviderpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "item"),
                name="app_metadataproviderpreference_unique_user_item",
            ),
        ),
    ]
