# Generated by Django 5.2.9 on 2026-03-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0102_itemproviderlink_metadataproviderpreference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="trakt_popularity_fetched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When Trakt popularity metadata was last fetched",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="trakt_popularity_rank",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Estimated Trakt popularity rank derived from the local score model",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="trakt_popularity_score",
            field=models.FloatField(
                blank=True,
                help_text="Derived Trakt popularity score computed from rating and votes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="trakt_rating",
            field=models.FloatField(
                blank=True,
                help_text="Average rating value from Trakt metadata",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="trakt_rating_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Rating count from Trakt metadata", null=True
            ),
        ),
        migrations.AlterField(
            model_name="metadatabackfillstate",
            name="field",
            field=models.CharField(
                choices=[
                    ("runtime", "Runtime"),
                    ("genres", "Genres"),
                    ("credits", "Credits"),
                    ("release", "Release Date"),
                    ("discover", "Discover Metadata"),
                    ("game_lengths", "Game Lengths"),
                    ("trakt_popularity", "Trakt Popularity"),
                ],
                max_length=20,
            ),
        ),
    ]
