# Generated by Django 5.2.9 on 2026-03-29 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0103_item_trakt_popularity_fetched_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(
                fields=["user", "status"], name="app_anime_user_id_beaed6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(
                fields=["user", "created_at"], name="app_anime_user_id_b178ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="basicmedia",
            index=models.Index(
                fields=["user", "status"], name="app_basicme_user_id_d61bfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="basicmedia",
            index=models.Index(
                fields=["user", "created_at"], name="app_basicme_user_id_16246b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardgame",
            index=models.Index(
                fields=["user", "status"], name="app_boardga_user_id_483879_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardgame",
            index=models.Index(
                fields=["user", "created_at"], name="app_boardga_user_id_e43fd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["user", "status"], name="app_book_user_id_7c1f60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["user", "created_at"], name="app_book_user_id_5892ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comic",
            index=models.Index(
                fields=["user", "status"], name="app_comic_user_id_9cff53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comic",
            index=models.Index(
                fields=["user", "created_at"], name="app_comic_user_id_f9f798_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "status"], name="app_game_user_id_958d22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "created_at"], name="app_game_user_id_f024e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(
                fields=["user", "status"], name="app_manga_user_id_08b94e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manga",
            index=models.Index(
                fields=["user", "created_at"], name="app_manga_user_id_fb6ebd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["user", "status"], name="app_movie_user_id_44d70c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["user", "created_at"], name="app_movie_user_id_ed4274_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="music",
            index=models.Index(
                fields=["user", "status"], name="app_music_user_id_c01bfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="music",
            index=models.Index(
                fields=["user", "created_at"], name="app_music_user_id_8be1ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["user", "status"], name="app_podcast_user_id_2f7287_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["user", "created_at"], name="app_podcast_user_id_3ff00e_idx"
            ),
        ),
    ]
