# Generated by Django 5.2.9 on 2026-03-30 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0104_add_media_user_status_created_at_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.DecimalValidator(3, 1),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
