# Generated by Django 5.2.9 on 2026-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0109_reopen_completed_tv_with_new_seasons"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="manual_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured metadata overrides for manual/custom entries",
            ),
        ),
    ]
