# Generated by Django 5.2.12 on 2026-04-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_widen_podcastepisode_audio_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='app_item_metadata_fetched_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='app_item_release_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='app_item_trakt_pop_rank_idx',
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='episode_uuid',
            field=models.CharField(help_text='Pocket Casts episode UUID', max_length=36, unique=True),
        ),
    ]
