# Generated by Django 5.2 on 2026-04-25

import logging

from django.db import migrations, transaction
from django.db.models import OuterRef, Subquery

logger = logging.getLogger(__name__)


def backfill_null_history_users(apps, schema_editor):
    HistoricalMusic = apps.get_model("app", "HistoricalMusic")
    HistoricalPodcast = apps.get_model("app", "HistoricalPodcast")
    Music = apps.get_model("app", "Music")
    Podcast = apps.get_model("app", "Podcast")

    def bulk_update_history(model, qs, user_id_field):
        with transaction.atomic():
            batch_size = 1000
            updated_count = 0

            for record in qs.iterator(chunk_size=batch_size):
                user_id = getattr(record, user_id_field, None)
                if not user_id:
                    continue
                model.objects.filter(id=record.id).update(history_user_id=user_id)
                updated_count += 1

            if updated_count > 0:
                logger.info("Updated %d %s records", updated_count, model.__name__)

    music_qs = HistoricalMusic.objects.filter(history_user_id__isnull=True).annotate(
        owner_user_id=Subquery(
            Music.objects.filter(id=OuterRef("id")).values("user_id")[:1],
        ),
    )
    bulk_update_history(HistoricalMusic, music_qs, "owner_user_id")

    podcast_qs = HistoricalPodcast.objects.filter(history_user_id__isnull=True).annotate(
        owner_user_id=Subquery(
            Podcast.objects.filter(id=OuterRef("id")).values("user_id")[:1],
        ),
    )
    bulk_update_history(HistoricalPodcast, podcast_qs, "owner_user_id")


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0114_item_provider_metadata_status"),
    ]

    operations = [
        migrations.RunPython(backfill_null_history_users, migrations.RunPython.noop),
    ]
