# Generated by Django 5.2.8 on 2025-12-14 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_plexaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plexaccount",
            options={
                "verbose_name": "Plex account",
                "verbose_name_plural": "Plex accounts",
            },
        ),
        migrations.CreateModel(
            name="PocketCastsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(help_text="Encrypted JWT access token"),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True, help_text="Encrypted refresh token", null=True
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pocketcasts_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pocket Casts account",
                "verbose_name_plural": "Pocket Casts accounts",
            },
        ),
    ]
