# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_pocketcastsaccount_connection_broken"),
    ]

    operations = [
        migrations.AddField(
            model_name="pocketcastsaccount",
            name="email",
            field=models.TextField(blank=True, help_text="Encrypted email address for login", null=True),
        ),
        migrations.AddField(
            model_name="pocketcastsaccount",
            name="password",
            field=models.TextField(blank=True, help_text="Encrypted password for login", null=True),
        ),
        migrations.AlterField(
            model_name="pocketcastsaccount",
            name="access_token",
            field=models.TextField(blank=True, help_text="Encrypted JWT access token (cached from login)", null=True),
        ),
    ]
