# Generated by Django 5.2.8 on 2025-12-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0004_pocketcastsaccount_email_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pocketcastsaccount",
            name="refresh_token",
            field=models.TextField(
                blank=True,
                help_text="Encrypted refresh token (cached from login)",
                null=True,
            ),
        ),
    ]
