# Generated by Django 5.2.9 on 2026-01-17 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0006_add_plex_account_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LastFMAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastfm_username", models.CharField(max_length=255)),
                (
                    "last_fetch_timestamp_uts",
                    models.IntegerField(
                        blank=True,
                        help_text="Unix timestamp (seconds) of last successful poll",
                        null=True,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection_broken",
                    models.BooleanField(
                        default=False,
                        help_text="True if connection is broken (invalid username or persistent errors)",
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        default=0, help_text="Number of consecutive failures"
                    ),
                ),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True,
                        help_text="Last.fm API error code (e.g., '29' for rate limit)",
                        max_length=10,
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True, help_text="Human-readable error message"
                    ),
                ),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lastfm_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Last.fm account",
                "verbose_name_plural": "Last.fm accounts",
            },
        ),
    ]
