# Generated by Django 5.2 on 2026-02-19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_traktaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudiobookshelfAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_url", models.URLField(help_text="Audiobookshelf server URL")),
                ("api_token", models.TextField(help_text="Encrypted Audiobookshelf API token")),
                ("sync_finished", models.BooleanField(default=True, help_text="Import finished items as completed entries")),
                ("create_missing", models.BooleanField(default=True, help_text="Create Yamtrack items when ABS items cannot be matched")),
                ("last_sync_ms", models.BigIntegerField(blank=True, help_text="Last imported Audiobookshelf progress timestamp (milliseconds)", null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("connection_broken", models.BooleanField(default=False)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="audiobookshelf_account", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Audiobookshelf account",
                "verbose_name_plural": "Audiobookshelf accounts",
            },
        ),
    ]
