# Generated by Django 5.2.9 on 2026-03-09 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0100_discovertasteprofile_comfort_library_affinity_and_more"),
        ("integrations", "0009_audiobookshelfaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plexaccount",
            name="watchlist_last_error",
            field=models.TextField(
                blank=True, default="", help_text="Last Plex watchlist sync error"
            ),
        ),
        migrations.AddField(
            model_name="plexaccount",
            name="watchlist_last_error_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plexaccount",
            name="watchlist_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plexaccount",
            name="watchlist_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether recurring Plex watchlist sync is enabled",
            ),
        ),
        migrations.CreateModel(
            name="PlexWatchlistSyncItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_username",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "source_account_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "plex_rating_key",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("plex_guid", models.CharField(blank=True, default="", max_length=255)),
                ("tmdb_id", models.CharField(blank=True, default="", max_length=32)),
                ("tvdb_id", models.CharField(blank=True, default="", max_length=32)),
                ("imdb_id", models.CharField(blank=True, default="", max_length=32)),
                ("created_by_sync", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plex_watchlist_sync_items",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plex_watchlist_sync_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plex watchlist sync item",
                "verbose_name_plural": "Plex watchlist sync items",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="integration_user_id_25f5f9_idx",
                    ),
                    models.Index(
                        fields=["user", "source_username"],
                        name="integration_user_id_75d930_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item", "source_username"),
                        name="integrations_plexwatchlistsyncitem_unique_user_item_source",
                    )
                ],
            },
        ),
    ]
