# Generated by Django 5.2.9 on 2026-03-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0010_plexaccount_watchlist_last_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lastfmaccount",
            name="history_import_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lastfmaccount",
            name="history_import_cutoff_uts",
            field=models.IntegerField(
                blank=True,
                help_text="Upper timestamp bound for the current history import",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lastfmaccount",
            name="history_import_last_error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lastfmaccount",
            name="history_import_next_page",
            field=models.PositiveIntegerField(
                default=1, help_text="Next Last.fm history page to import"
            ),
        ),
        migrations.AddField(
            model_name="lastfmaccount",
            name="history_import_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lastfmaccount",
            name="history_import_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                ],
                default="idle",
                help_text="Current Last.fm history import state",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lastfmaccount",
            name="history_import_total_pages",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total page count reported by Last.fm for the current history import",
                null=True,
            ),
        ),
    ]
