# Generated by Django 5.2.8 on 2025-12-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0003_alter_customlist_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customlist",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                max_length=10,
            ),
        ),
    ]
