# Generated by Django 5.2.9 on 2026-01-19 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0003_customlist_source_fields"),
        ("lists", "0005_add_recommendations_activity"),
    ]

    operations = []
