# Generated by Django 5.2.9 on 2026-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0006_merge_20260119_2310"),
    ]

    operations = [
        migrations.AddField(
            model_name="customlist",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional tags used to group public lists.",
            ),
        ),
    ]
