# Generated by Django 5.2.2 on 2025-08-06 11:47

from django.db import migrations, models


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_update_repeating_status"),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name="user",
            name="home_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="home_sort",
            field=models.CharField(
                choices=[
                    ("recent", "Recent"),
                    ("upcoming", "Upcoming"),
                    ("completion", "Completion"),
                    ("episodes_left", "Episodes Left"),
                    ("title", "Title"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
