# Generated by Django 5.2.2 on 2025-08-17 14:44

from django.db import migrations, models
from django.db import connection
import json
import os


def check_constraint_values(apps, schema_editor):
    """Check all constraint-related field values before migration to identify invalid data."""
    # #region agent log
    log_path = "/Users/dannyvfilms/Developer/Cursor/release/.cursor/debug.log"
    try:
        User = apps.get_model("users", "User")
        users = User.objects.all()
        invalid_fields = {}
        
        # Valid values for each constraint
        # Include values that may be added in later migrations but exist in data
        valid_values = {
            "last_search_type": [
                "tv",
                "movie",
                "anime",
                "manga",
                "game",
                "book",
                "comic",
                "boardgame",
                "music",
                "podcast",
            ],
            "tv_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "season_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "movie_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "anime_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "manga_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "game_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "book_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "list_detail_sort": [
                "date_added",
                "title",
                "media_type",
                "rating",
                "progress",
                "start_date",
                "end_date",
            ],
        }
        
        for user in users:
            for field_name, valid_list in valid_values.items():
                if hasattr(user, field_name):
                    value = getattr(user, field_name, None)
                    if value not in valid_list + [None, ""]:
                        if field_name not in invalid_fields:
                            invalid_fields[field_name] = []
                        invalid_fields[field_name].append({
                            "id": user.id,
                            "username": user.username,
                            "value": value,
                        })
        
        log_entry = {
            "sessionId": "debug-session",
            "runId": "pre-migration-check",
            "hypothesisId": "A",
            "location": "0038_migration:check_constraint_values",
            "message": "Checking constraint field values before migration",
            "data": {
                "total_users": users.count(),
                "invalid_fields": invalid_fields,
            },
            "timestamp": int(__import__("time").time() * 1000),
        }
        with open(log_path, "a") as f:
            f.write(json.dumps(log_entry) + "\n")
    except Exception as e:
        log_entry = {
            "sessionId": "debug-session",
            "runId": "pre-migration-check",
            "hypothesisId": "A",
            "location": "0038_migration:check_constraint_values",
            "message": "Error checking constraint values",
            "data": {"error": str(e)},
            "timestamp": int(__import__("time").time() * 1000),
        }
        with open(log_path, "a") as f:
            f.write(json.dumps(log_entry) + "\n")
    # #endregion


def fix_invalid_constraint_values(apps, schema_editor):
    """Fix invalid constraint field values using raw SQL to avoid ORM issues."""
    # #region agent log
    log_path = "/Users/dannyvfilms/Developer/Cursor/release/.cursor/debug.log"
    try:
        from django.db import connection
        
        fixed_counts = {}
        
        # Default values and valid values for each constraint
        field_defaults = {
            "last_search_type": "tv",
            "tv_sort": "score",
            "season_sort": "score",
            "movie_sort": "score",
            "anime_sort": "score",
            "manga_sort": "score",
            "game_sort": "score",
            "book_sort": "score",
            "list_detail_sort": "date_added",
        }
        
        valid_values = {
            "last_search_type": [
                "tv",
                "movie",
                "anime",
                "manga",
                "game",
                "book",
                "comic",
                "boardgame",
                "music",
                "podcast",
            ],
            "tv_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "season_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "movie_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "anime_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "manga_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "game_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "book_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "list_detail_sort": [
                "date_added",
                "title",
                "media_type",
                "rating",
                "progress",
                "start_date",
                "end_date",
            ],
        }
        
        with connection.cursor() as cursor:
            # Check if table exists and has the columns
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='users_user'")
            if not cursor.fetchone():
                return  # Table doesn't exist yet
            
            # Get column names
            cursor.execute("PRAGMA table_info(users_user)")
            columns = [row[1] for row in cursor.fetchall()]
            
            for field_name, default_value in field_defaults.items():
                if field_name not in columns:
                    continue  # Column doesn't exist yet
                
                valid_list = valid_values.get(field_name, [])
                if not valid_list:
                    continue
                
                # Build SQL to find and fix invalid values
                # Use parameterized query properly - field name in f-string, values as parameters
                placeholders = ",".join(["?"] * len(valid_list))
                try:
                    # Build the query string with field name, then pass values as parameters
                    query = f"""
                        SELECT id, username, {field_name} 
                        FROM users_user 
                        WHERE {field_name} IS NOT NULL 
                        AND {field_name} != '' 
                        AND {field_name} NOT IN ({placeholders})
                        """
                    cursor.execute(query, valid_list)
                    invalid_rows = cursor.fetchall()
                    
                    for user_id, username, old_value in invalid_rows:
                        # Fix the invalid value
                        cursor.execute(
                            f"UPDATE users_user SET {field_name} = ? WHERE id = ?",
                            [default_value, user_id],
                        )
                        fixed_counts[field_name] = fixed_counts.get(field_name, 0) + 1
                        
                        log_entry = {
                            "sessionId": "debug-session",
                            "runId": "pre-migration-fix",
                            "hypothesisId": "A",
                            "location": "0038_migration:fix_invalid_constraint_values",
                            "message": f"Fixed invalid {field_name} value",
                            "data": {
                                "user_id": user_id,
                                "username": username,
                                "field": field_name,
                                "old_value": old_value,
                                "new_value": default_value,
                            },
                            "timestamp": int(__import__("time").time() * 1000),
                        }
                        with open(log_path, "a") as f:
                            f.write(json.dumps(log_entry) + "\n")
                except Exception as field_error:
                    log_entry = {
                        "sessionId": "debug-session",
                        "runId": "pre-migration-fix",
                        "hypothesisId": "A",
                        "location": "0038_migration:fix_invalid_constraint_values",
                        "message": f"Error fixing {field_name}",
                        "data": {"error": str(field_error)},
                        "timestamp": int(__import__("time").time() * 1000),
                    }
                    with open(log_path, "a") as f:
                        f.write(json.dumps(log_entry) + "\n")
        
        log_entry = {
            "sessionId": "debug-session",
            "runId": "pre-migration-fix",
            "hypothesisId": "A",
            "location": "0038_migration:fix_invalid_constraint_values",
            "message": "Completed fixing invalid constraint values",
            "data": {"fixed_counts": fixed_counts},
            "timestamp": int(__import__("time").time() * 1000),
        }
        with open(log_path, "a") as f:
            f.write(json.dumps(log_entry) + "\n")
    except Exception as e:
        log_entry = {
            "sessionId": "debug-session",
            "runId": "pre-migration-fix",
            "hypothesisId": "A",
            "location": "0038_migration:fix_invalid_constraint_values",
            "message": "Error fixing constraint values",
            "data": {"error": str(e)},
            "timestamp": int(__import__("time").time() * 1000),
        }
        with open(log_path, "a") as f:
            f.write(json.dumps(log_entry) + "\n")
    # #endregion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0051_migrate_simkl_periodoc_tasks"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0037_remove_user_home_sort_valid_alter_user_home_sort"),
    ]

    operations = [
        migrations.RunPython(check_constraint_values, migrations.RunPython.noop),
        migrations.RunPython(fix_invalid_constraint_values, migrations.RunPython.noop),
        # Remove ALL CHECK constraints before adding fields (SQLite needs this during table recreation)
        # These constraints exist from previous migrations and will be re-added after fields are added
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=migrations.RunSQL.noop,  # Django will handle constraint removal during table recreation
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                # Remove all CHECK constraints from Django's state that exist at this point
                # These constraints exist from previous migrations and will be re-added after fields are added
                migrations.RemoveConstraint(model_name="user", name="last_search_type_valid"),
                migrations.RemoveConstraint(model_name="user", name="tv_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="season_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="movie_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="anime_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="manga_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="game_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="book_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="list_detail_sort_valid"),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default (locale)"),
                    ("iso_8601", "ISO 8601"),
                    ("month_d_yyyy", "Month D, YYYY"),
                    ("d_mon_yyyy", "D Mon YYYY"),
                    ("m_d_yyyy", "M/D/YYYY"),
                    ("d_m_yyyy", "D/M/YYYY"),
                    ("dd_mm_yyyy", "DD.MM.YYYY"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default (locale)"),
                    ("h_mm_ampm", "12-hour (h:mm AM/PM)"),
                    ("hh_mm_ampm", "12-hour, leading zero (hh:mm AM/PM)"),
                    ("hh_mm", "24-hour (HH:mm)"),
                    ("hh_mm_ss", "24-hour with seconds (HH:mm:ss)"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Fix data again AFTER fields are added but BEFORE re-adding constraints
        # SQLite will recreate the table when adding constraints, so we need valid data
        migrations.RunPython(fix_invalid_constraint_values, migrations.RunPython.noop),
        # Log values right before adding constraints to debug
        migrations.RunPython(
            lambda apps, schema_editor: check_constraint_values(apps, schema_editor),
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "home_sort__in",
                        ["recent", "upcoming", "completion", "episodes_left", "title"],
                    )
                ),
                name="home_sort_valid",
            ),
        ),
        # Re-add all CHECK constraints after fields are added
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                        (
                            "tv_sort__in",
                            ["score", "title", "progress", "start_date", "end_date", "time_left"],
                        )
                ),
                name="tv_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "season_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="season_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movie_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="movie_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "anime_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="anime_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "manga_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="manga_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "game_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="game_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "book_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="book_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                        (
                            "list_detail_sort__in",
                        [
                            "date_added",
                            "title",
                            "media_type",
                            "rating",
                            "progress",
                            "start_date",
                            "end_date",
                        ],
                        )
                ),
                name="list_detail_sort_valid",
            ),
        ),
    ]
