# Generated by Django 5.2.2 on 2025-08-17 14:44

from django.db import migrations, models
import logging


def drop_home_sort_constraint_if_exists(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE users_user DROP CONSTRAINT IF EXISTS home_sort_valid;",
    )


def drop_all_constraints_if_exists(apps, schema_editor):
    """Drop all CHECK constraints on Postgres to avoid DuplicateObject errors."""
    if schema_editor.connection.vendor != "postgresql":
        return
    constraints = [
        "last_search_type_valid",
        "tv_sort_valid",
        "season_sort_valid",
        "movie_sort_valid",
        "anime_sort_valid",
        "manga_sort_valid",
        "game_sort_valid",
        "book_sort_valid",
        "list_detail_sort_valid",
        "home_sort_valid",
    ]
    with schema_editor.connection.cursor() as cursor:
        for constraint in constraints:
            cursor.execute(f"ALTER TABLE users_user DROP CONSTRAINT IF EXISTS {constraint};")


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        field = from_model._meta.get_field(self.name)
        if not _column_exists(schema_editor, from_model._meta.db_table, field.column):
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def check_constraint_values(apps, schema_editor):
    """Check all constraint-related field values before migration to identify invalid data."""
    logger = logging.getLogger(__name__)
    try:
        User = apps.get_model("users", "User")
        users = User.objects.all()
        invalid_fields = {}
        
        # Valid values for each constraint
        # Include values that may be added in later migrations but exist in data
        valid_values = {
            "last_search_type": [
                "tv",
                "movie",
                "anime",
                "manga",
                "game",
                "book",
                "comic",
                "boardgame",
                "music",
                "podcast",
            ],
            "tv_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "season_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "movie_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "anime_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "manga_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "game_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "book_sort": ["score", "title", "progress", "start_date", "end_date", "time_left"],
            "list_detail_sort": [
                "date_added",
                "title",
                "media_type",
                "rating",
                "progress",
                "start_date",
                "end_date",
            ],
        }
        
        for user in users:
            for field_name, valid_list in valid_values.items():
                if hasattr(user, field_name):
                    value = getattr(user, field_name, None)
                    if value not in valid_list + [None, ""]:
                        if field_name not in invalid_fields:
                            invalid_fields[field_name] = []
                        invalid_fields[field_name].append({
                            "id": user.id,
                            "username": user.username,
                            "value": value,
                        })

        if invalid_fields:
            logger.warning(
                "Invalid constraint values detected in users migration check: %s",
                invalid_fields,
            )
    except Exception as e:
        logger.warning("Error checking constraint values: %s", e)


def fix_invalid_constraint_values(apps, schema_editor):
    """Fix invalid constraint field values using raw SQL to avoid ORM issues."""
    logger = logging.getLogger(__name__)
    try:
        fixed_counts = {}
        
        # Default values and valid values for each constraint
        field_defaults = {
            "last_search_type": "tv",
            "tv_sort": "score",
            "season_sort": "score",
            "movie_sort": "score",
            "anime_sort": "score",
            "manga_sort": "score",
            "game_sort": "score",
            "book_sort": "score",
            "list_detail_sort": "date_added",
        }
        
        valid_values = {
            "last_search_type": [
                "tv",
                "movie",
                "anime",
                "manga",
                "game",
                "book",
                "comic",
                "boardgame",
                "music",
                "podcast",
            ],
            "tv_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "season_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "movie_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "anime_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "manga_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "game_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "book_sort": [
                "score",
                "title",
                "progress",
                "start_date",
                "end_date",
                "time_left",
            ],
            "list_detail_sort": [
                "date_added",
                "title",
                "media_type",
                "rating",
                "progress",
                "start_date",
                "end_date",
            ],
        }
        
        with schema_editor.connection.cursor() as cursor:
            # Check if table exists and has the columns
            introspection = schema_editor.connection.introspection
            if hasattr(introspection, "table_names"):
                table_names = introspection.table_names(cursor)
            else:
                table_names = [table.name for table in introspection.get_table_list(cursor)]
            if "users_user" not in table_names:
                return  # Table doesn't exist yet

            description = introspection.get_table_description(cursor, "users_user")
            columns = {getattr(column, "name", column[0]) for column in description}
            
            for field_name, default_value in field_defaults.items():
                if field_name not in columns:
                    continue  # Column doesn't exist yet
                
                valid_list = valid_values.get(field_name, [])
                if not valid_list:
                    continue
                
                # Build SQL to find and fix invalid values
                # Use parameterized query properly - field name in f-string, values as parameters
                placeholders = ",".join(["%s"] * len(valid_list))
                try:
                    # Build the query string with field name, then pass values as parameters
                    query = f"""
                        SELECT id, username, {field_name} 
                        FROM users_user 
                        WHERE {field_name} IS NOT NULL 
                        AND {field_name} != '' 
                        AND {field_name} NOT IN ({placeholders})
                        """
                    cursor.execute(query, valid_list)
                    invalid_rows = cursor.fetchall()
                    
                    for user_id, username, old_value in invalid_rows:
                        # Fix the invalid value
                        cursor.execute(
                            f"UPDATE users_user SET {field_name} = %s WHERE id = %s",
                            [default_value, user_id],
                        )
                        fixed_counts[field_name] = fixed_counts.get(field_name, 0) + 1
                except Exception as field_error:
                    logger.warning("Error fixing %s: %s", field_name, field_error)

        if fixed_counts:
            logger.info("Fixed invalid constraint values: %s", fixed_counts)
    except Exception as e:
        logger.warning("Error fixing constraint values: %s", e)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0051_migrate_simkl_periodoc_tasks"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0037_remove_user_home_sort_valid_alter_user_home_sort"),
    ]

    operations = [
        migrations.RunPython(check_constraint_values, migrations.RunPython.noop),
        migrations.RunPython(fix_invalid_constraint_values, migrations.RunPython.noop),
        # Remove ALL CHECK constraints before adding fields (SQLite needs this during table recreation)
        # These constraints exist from previous migrations and will be re-added after fields are added
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_all_constraints_if_exists,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                # Remove all CHECK constraints from Django's state that exist at this point
                # These constraints exist from previous migrations and will be re-added after fields are added
                migrations.RemoveConstraint(model_name="user", name="last_search_type_valid"),
                migrations.RemoveConstraint(model_name="user", name="tv_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="season_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="movie_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="anime_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="manga_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="game_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="book_sort_valid"),
                migrations.RemoveConstraint(model_name="user", name="list_detail_sort_valid"),
            ],
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default (locale)"),
                    ("iso_8601", "ISO 8601"),
                    ("month_d_yyyy", "Month D, YYYY"),
                    ("d_mon_yyyy", "D Mon YYYY"),
                    ("m_d_yyyy", "M/D/YYYY"),
                    ("d_m_yyyy", "D/M/YYYY"),
                    ("dd_mm_yyyy", "DD.MM.YYYY"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default (locale)"),
                    ("h_mm_ampm", "12-hour (h:mm AM/PM)"),
                    ("hh_mm_ampm", "12-hour, leading zero (hh:mm AM/PM)"),
                    ("hh_mm", "24-hour (HH:mm)"),
                    ("hh_mm_ss", "24-hour with seconds (HH:mm:ss)"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            drop_home_sort_constraint_if_exists,
            migrations.RunPython.noop,
        ),
        # Fix data again AFTER fields are added but BEFORE re-adding constraints
        # SQLite will recreate the table when adding constraints, so we need valid data
        migrations.RunPython(fix_invalid_constraint_values, migrations.RunPython.noop),
        # Log values right before adding constraints to debug
        migrations.RunPython(
            lambda apps, schema_editor: check_constraint_values(apps, schema_editor),
            migrations.RunPython.noop,
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "home_sort__in",
                        ["recent", "upcoming", "completion", "episodes_left", "title"],
                    )
                ),
                name="home_sort_valid",
            ),
        ),
        # Re-add all CHECK constraints after fields are added
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                        (
                            "tv_sort__in",
                            ["score", "title", "progress", "start_date", "end_date", "time_left"],
                        )
                ),
                name="tv_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "season_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="season_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movie_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="movie_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "anime_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="anime_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "manga_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="manga_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "game_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="game_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "book_sort__in",
                        ["score", "title", "progress", "start_date", "end_date", "time_left"],
                    )
                ),
                name="book_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                        (
                            "list_detail_sort__in",
                        [
                            "date_added",
                            "title",
                            "media_type",
                            "rating",
                            "progress",
                            "start_date",
                            "end_date",
                        ],
                        )
                ),
                name="list_detail_sort_valid",
            ),
        ),
    ]
