# Generated by Django 5.2.7 on 2025-11-26 09:34

from django.db import migrations, models


def drop_home_sort_constraint_if_exists(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE users_user DROP CONSTRAINT IF EXISTS home_sort_valid;",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_item_title'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0037_remove_user_home_sort_valid_alter_user_home_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_sort',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('recent', 'Recent'), ('completion', 'Completion'), ('episodes_left', 'Episodes Left'), ('title', 'Title')], default='upcoming', max_length=20),
        ),
        migrations.RunPython(
            drop_home_sort_constraint_if_exists,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('home_sort__in', ['upcoming', 'recent', 'completion', 'episodes_left', 'title'])), name='home_sort_valid'),
        ),
    ]
