# Generated by Django 5.2.2 on 2025-08-17 17:45

from django.db import migrations, models


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def drop_home_sort_constraint_if_exists(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE users_user DROP CONSTRAINT IF EXISTS home_sort_valid;",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0051_migrate_simkl_periodoc_tasks"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0037_remove_user_home_sort_valid_alter_user_home_sort"),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name="user",
            name="list_detail_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="list_detail_sort",
            field=models.CharField(
                choices=[
                    ("date_added", "Date Added"),
                    ("title", "Title"),
                    ("media_type", "Media Type"),
                    ("rating", "Rating"),
                ],
                default="date_added",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            drop_home_sort_constraint_if_exists,
            migrations.RunPython.noop,
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "home_sort__in",
                        ["recent", "upcoming", "completion", "episodes_left", "title"],
                    )
                ),
                name="home_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "list_detail_sort__in",
                        ["date_added", "title", "media_type", "rating"],
                    )
                ),
                name="list_detail_sort_valid",
            ),
        ),
    ]
