# Generated by Django 5.2.9 on 2026-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_add_quick_watch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress_bar',
            field=models.BooleanField(default=False, help_text='Show progress bar'),
        ),
    ]
