# Generated by Django 5.2.9 on 2026-01-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_add_date_time_format_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress_bar',
            field=models.BooleanField(default=False, help_text='Show progress bar'),
        ),
    ]
