# Generated by Django 5.2.6 on 2025-11-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0053_item_release_datetime"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0044_merge_20251115_1520"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="home_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="home_sort_valid",
        ),
        migrations.AddField(
            model_name="user",
            name="activity_history_view",
            field=models.CharField(
                choices=[
                    ("activity_heatmap", "Activity Heatmap"),
                    ("stacked_bar_chart", "Stacked Bar Chart"),
                ],
                default="activity_heatmap",
                help_text="How to render Activity History on the Statistics page",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "activity_history_view__in",
                        ["activity_heatmap", "stacked_bar_chart"],
                    )
                ),
                name="activity_history_view_valid",
            ),
        ),
    ]
