# Generated by Django 5.2.6 on 2025-11-21 17:31

from django.db import migrations, models


def ensure_auto_pause_columns(apps, schema_editor):
    """Ensure auto-pause columns exist with valid JSON before table rebuilds."""
    connection = schema_editor.connection
    vendor = connection.vendor

    with connection.cursor() as cursor:
        column_types = {}

        if vendor == "sqlite":
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='users_user'"
            )
            if not cursor.fetchone():
                return

            cursor.execute("PRAGMA table_info(users_user)")
            for row in cursor.fetchall():
                column_types[row[1]] = row[2]

        elif vendor == "postgresql":
            cursor.execute(
                "SELECT column_name, data_type FROM information_schema.columns "
                "WHERE table_schema = current_schema() AND table_name = %s",
                ["users_user"],
            )
            for column_name, data_type in cursor.fetchall():
                column_types[column_name] = data_type
            if not column_types:
                return

        else:
            return

        if "auto_pause_in_progress_enabled" not in column_types:
            if vendor == "postgresql":
                cursor.execute(
                    "ALTER TABLE users_user "
                    "ADD COLUMN auto_pause_in_progress_enabled boolean NOT NULL DEFAULT false"
                )
            else:
                cursor.execute(
                    "ALTER TABLE users_user "
                    "ADD COLUMN auto_pause_in_progress_enabled bool NOT NULL DEFAULT 0"
                )

        rules_type = column_types.get("auto_pause_rules")
        if rules_type is None:
            if vendor == "postgresql":
                cursor.execute(
                    "ALTER TABLE users_user "
                    "ADD COLUMN auto_pause_rules jsonb NOT NULL DEFAULT '[]'::jsonb"
                )
                rules_type = "jsonb"
            else:
                cursor.execute(
                    "ALTER TABLE users_user "
                    "ADD COLUMN auto_pause_rules TEXT NOT NULL DEFAULT '[]'"
                )
                rules_type = "text"

        if vendor == "sqlite":
            try:
                cursor.execute(
                    "UPDATE users_user SET auto_pause_rules = '[]' "
                    "WHERE auto_pause_rules IS NULL OR JSON_VALID(auto_pause_rules) = 0"
                )
            except Exception:
                cursor.execute(
                    "UPDATE users_user SET auto_pause_rules = '[]' "
                    "WHERE auto_pause_rules IS NULL "
                    "OR auto_pause_rules = '' "
                    "OR auto_pause_rules = 'auto_pause_rules'"
                )
        elif vendor == "postgresql":
            if rules_type == "json":
                cursor.execute(
                    "UPDATE users_user SET auto_pause_rules = '[]'::json "
                    "WHERE auto_pause_rules IS NULL"
                )
            elif rules_type == "jsonb":
                cursor.execute(
                    "UPDATE users_user SET auto_pause_rules = '[]'::jsonb "
                    "WHERE auto_pause_rules IS NULL"
                )
            else:
                cursor.execute(
                    "UPDATE users_user SET auto_pause_rules = '[]' "
                    "WHERE auto_pause_rules IS NULL "
                    "OR auto_pause_rules = '' "
                    "OR auto_pause_rules = 'auto_pause_rules'"
                )


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0053_item_release_datetime"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0044_merge_20251115_1520"),
    ]

    operations = [
        migrations.RunPython(ensure_auto_pause_columns, migrations.RunPython.noop),
        RemoveConstraintIfExists(
            model_name="user",
            name="home_sort_valid",
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="activity_history_view",
            field=models.CharField(
                choices=[
                    ("heatmap", "Activity Heatmap"),
                    ("stacked", "Stacked Bar Chart"),
                ],
                default="heatmap",
                help_text="Which activity history visualization to show on the Statistics page",
                max_length=20,
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "activity_history_view__in",
                        ["heatmap", "stacked"],
                    )
                ),
                name="activity_history_view_valid",
            ),
        ),
    ]
