# Generated by assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0044_merge_20251115_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activity_history_view",
            field=models.CharField(
                choices=[('heatmap', 'Activity Heatmap'), ('stacked', 'Stacked Bar Chart')],
                default='heatmap',
                max_length=20,
            ),
        ),
    ]
