# Generated by Django 5.2.8 on 2025-12-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0056_add_music_media_type"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0049_remove_user_last_search_type_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="last_search_type_valid",
        ),
        migrations.AddField(
            model_name="user",
            name="music_direction",
            field=models.CharField(
                choices=[("asc", "Ascending"), ("desc", "Descending")],
                default="desc",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="music_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="music_layout",
            field=models.CharField(
                choices=[("grid", "Grid"), ("table", "Table")],
                default="grid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="music_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="music_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_search_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                ],
                default="tv",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("music_layout__in", ["grid", "table"])),
                name="music_layout_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "music_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="music_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("music_direction__in", ["asc", "desc"])),
                name="music_direction_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "music_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planning",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="music_status_valid",
            ),
        ),
    ]
