# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0056_add_music_media_type"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0050_add_music_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_grid_layout",
            field=models.CharField(
                choices=[
                    ("comfortable", "Comfortable (2 columns)"),
                    ("compact", "Compact (3 columns)"),
                ],
                default="compact",
                help_text="Number of columns to show on mobile layouts",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="quick_season_update_mobile",
            field=models.BooleanField(
                default=False,
                help_text="Show the quick season update button on mobile episode lists",
            ),
        ),
    ]
