# Generated by Django 5.2.8 on 2025-12-14 15:26

from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0063_historicalpodcast_podcast_podcastepisode_podcastshow_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0051_add_mobile_preferences"),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name="user",
            name="last_search_type_valid",
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="podcast_direction",
            field=models.CharField(
                choices=[("asc", "Ascending"), ("desc", "Descending")],
                default="desc",
                max_length=4,
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="podcast_enabled",
            field=models.BooleanField(default=True),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="podcast_layout",
            field=models.CharField(
                choices=[("grid", "Grid"), ("table", "Table")],
                default="grid",
                max_length=20,
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="podcast_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="title",
                max_length=20,
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="podcast_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_search_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                ],
                default="tv",
                max_length=10,
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("podcast_layout__in", ["grid", "table"])),
                name="podcast_layout_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "podcast_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="podcast_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("podcast_direction__in", ["asc", "desc"])),
                name="podcast_direction_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "podcast_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planning",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="podcast_status_valid",
            ),
        ),
    ]
