# Generated by Django 5.2.8 on 2025-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0052_remove_user_last_search_type_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_planned_on_home",
            field=models.BooleanField(
                default=False,
                help_text="Show planned items on the home screen alongside in-progress items",
            ),
        ),
    ]
