# Generated by Django 5.2.8 on 2025-12-18 16:30

from django.db import migrations, models


def convert_boolean_to_choice(apps, schema_editor):
    """Convert boolean values to choice values."""
    from django.db import connection
    with connection.cursor() as cursor:
        # Read old boolean values and write to temp char field
        cursor.execute("SELECT id, show_planned_on_home FROM users_user")
        for user_id, old_value in cursor.fetchall():
            new_value = "combined" if old_value else "disabled"
            cursor.execute(
                "UPDATE users_user SET show_planned_on_home_temp = %s WHERE id = %s",
                [new_value, user_id]
            )


def reverse_convert_choice_to_boolean(apps, schema_editor):
    """Reverse: convert choice values back to boolean - not fully reversible."""
    pass  # Reverse migration not needed as this is a one-way upgrade


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0053_add_show_planned_on_home"),
    ]

    operations = [
        # Add temporary CharField
        migrations.AddField(
            model_name="user",
            name="show_planned_on_home_temp",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("combined", "Combined"),
                    ("separated", "Separated"),
                ],
                default="disabled",
                max_length=20,
                null=True,
            ),
        ),
        # Migrate data
        migrations.RunPython(convert_boolean_to_choice, reverse_convert_choice_to_boolean),
        # Remove old field
        migrations.RemoveField(
            model_name="user",
            name="show_planned_on_home",
        ),
        # Rename temp field
        migrations.RenameField(
            model_name="user",
            old_name="show_planned_on_home_temp",
            new_name="show_planned_on_home",
        ),
        # Set final field properties
        migrations.AlterField(
            model_name="user",
            name="show_planned_on_home",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("combined", "Combined"),
                    ("separated", "Separated"),
                ],
                default="disabled",
                help_text="Show planned items on the home screen alongside in-progress items",
                max_length=20,
            ),
        ),
    ]
