# Generated by Django 5.2.9 on 2025-12-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_convert_show_planned_on_home_to_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jellyseerr_allowed_usernames',
            field=models.TextField(blank=True, help_text='Comma-separated list of Jellyseerr usernames allowed to trigger adds. Blank = allow all.'),
        ),
        migrations.AddField(
            model_name='user',
            name='jellyseerr_default_added_status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('In progress', 'In Progress')], default='Planning', help_text='Status to set when adding media via Jellyseerr webhook', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='jellyseerr_enabled',
            field=models.BooleanField(default=False, help_text='Enable Jellyseerr webhook auto-add for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='jellyseerr_trigger_statuses',
            field=models.TextField(blank=True, help_text='Comma-separated Jellyseerr media_status values that trigger add (e.g. PENDING,PROCESSING,AVAILABLE). Blank = default behaviour (skips UNKNOWN).'),
        ),
    ]
