# Generated by Django 5.2.9 on 2025-12-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_user_jellyseerr_allowed_usernames_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="statistics_default_range",
            field=models.CharField(
                choices=[
                    ("Today", "Today"),
                    ("Yesterday", "Yesterday"),
                    ("This Week", "This Week"),
                    ("Last 7 Days", "Last 7 Days"),
                    ("This Month", "This Month"),
                    ("Last 30 Days", "Last 30 Days"),
                    ("Last 90 Days", "Last 90 Days"),
                    ("This Year", "This Year"),
                    ("Last 6 Months", "Last 6 Months"),
                    ("Last 12 Months", "Last 12 Months"),
                    ("All Time", "All Time"),
                ],
                default="Last 12 Months",
                help_text="Default predefined range for the Statistics page",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                name="statistics_default_range_valid",
                condition=models.Q(
                    statistics_default_range__in=[
                        "Today",
                        "Yesterday",
                        "This Week",
                        "Last 7 Days",
                        "This Month",
                        "Last 30 Days",
                        "Last 90 Days",
                        "This Year",
                        "Last 6 Months",
                        "Last 12 Months",
                        "All Time",
                    ],
                ),
            ),
        ),
    ]
