# Generated by Django 5.2.9 on 2025-12-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_add_statistics_default_range"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="list_detail_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="list_detail_sort",
            field=models.CharField(
                choices=[
                    ("date_added", "Date Added"),
                    ("title", "Title"),
                    ("media_type", "Media Type"),
                    ("rating", "Rating"),
                    ("progress", "Progress"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="date_added",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    list_detail_sort__in=[
                        "date_added",
                        "title",
                        "media_type",
                        "rating",
                        "progress",
                        "start_date",
                        "end_date",
                    ],
                ),
                name="list_detail_sort_valid",
            ),
        ),
    ]
