# Generated by Django 5.2.9 on 2026-01-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0057_add_list_detail_sort_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="book_comic_manga_progress_percentage",
            field=models.BooleanField(
                default=False,
                help_text="Track book, comic, and manga progress as percentage instead of pages/issues/chapters",
            ),
        ),
    ]
