# Generated by Django 5.2.9 on 2026-01-27 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_add_boardgame_preferences"),
        ("users", "0058_add_book_comic_manga_progress_percentage"),
    ]

    operations = []
