# Generated by Django 5.2.9 on 2026-01-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0075_remove_item_app_item_source_valid_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0059_merge_20260127_1754"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="last_search_type_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="boardgame_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default (locale)"),
                    ("iso_8601", "ISO 8601"),
                    ("month_d_yyyy", "Month D, YYYY"),
                    ("d_mon_yyyy", "D Mon YYYY"),
                    ("m_d_yyyy", "M/D/YYYY"),
                    ("d_m_yyyy", "D/M/YYYY"),
                    ("dd_mm_yyyy", "DD.MM.YYYY"),
                    ("yyyy_mm_dd", "YYYY/MM/DD"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_search_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                ],
                default="tv",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default (locale)"),
                    ("h_mm_ampm", "12-hour (h:mm AM/PM)"),
                    ("hh_mm_ampm", "12-hour, leading zero (hh:mm AM/PM)"),
                    ("hh_mm", "24-hour (HH:mm)"),
                    ("hh_mm_ss", "24-hour with seconds (HH:mm:ss)"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
    ]
