# Generated by Django 5.2.9 on 2026-02-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0060_remove_user_last_search_type_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="media_card_subtitle_display",
            field=models.CharField(
                choices=[("hover", "On hover"), ("always", "Always visible")],
                default="hover",
                help_text="Control when media card subtitles are visible",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("media_card_subtitle_display__in", ["hover", "always"])
                ),
                name="media_card_subtitle_display_valid",
            ),
        ),
    ]
