# Generated by Django 5.2.9 on 2026-02-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0075_remove_item_app_item_source_valid_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0061_add_media_card_subtitle_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rating_scale",
            field=models.CharField(
                choices=[("10", "1-10 stars"), ("5", "1-5 stars")],
                default="10",
                help_text="Preferred rating scale for user scores",
                max_length=2,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating_scale__in", ["10", "5"])),
                name="rating_scale_valid",
            ),
        ),
    ]
