# Generated by Django 5.2.9 on 2026-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0062_user_rating_scale_user_rating_scale_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plex_webhook_last_received_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Timestamp of the last Plex webhook received",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="plex_webhook_last_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Last Plex webhook error message",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="plex_webhook_last_error_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Timestamp of the last Plex webhook error",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="plex_webhook_token_rotated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the API token was regenerated (update webhook URLs)",
            ),
        ),
    ]
