# Generated by Django 5.2.9 on 2026-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0084_item_localized_title_item_original_title"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0065_add_table_column_prefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="title_display_preference",
            field=models.CharField(
                choices=[
                    ("localized", "Show Localized Titles"),
                    ("original", "Show Original Titles"),
                    ("auto", "Auto (if available)"),
                ],
                default="localized",
                help_text="Preferred title variant to display in the UI",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title_display_preference__in", ["localized", "original", "auto"])
                ),
                name="title_display_preference_valid",
            ),
        ),
    ]
