# Generated by Django 5.2.9 on 2026-02-15 00:54

import json

from django.db import migrations, models


def _normalize_invalid_auto_pause_rules(apps, schema_editor):
    """Ensure SQLite table remakes don't fail on invalid JSON values."""
    if schema_editor.connection.vendor != "sqlite":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(users_user)")
        existing_columns = {row[1] for row in cursor.fetchall()}
        if "auto_pause_rules" not in existing_columns:
            return

        cursor.execute("SELECT id, auto_pause_rules FROM users_user")
        rows = cursor.fetchall()

        invalid_row_ids = []
        for row_id, raw_value in rows:
            if raw_value in (None, "", "auto_pause_rules"):
                invalid_row_ids.append(row_id)
                continue

            parsed_value = None
            if isinstance(raw_value, bytes):
                try:
                    raw_value = raw_value.decode("utf-8")
                except UnicodeDecodeError:
                    invalid_row_ids.append(row_id)
                    continue

            if not isinstance(raw_value, str):
                invalid_row_ids.append(row_id)
                continue

            try:
                parsed_value = json.loads(raw_value)
            except json.JSONDecodeError:
                invalid_row_ids.append(row_id)
                continue

            if not isinstance(parsed_value, list):
                invalid_row_ids.append(row_id)

        for row_id in invalid_row_ids:
            cursor.execute(
                "UPDATE users_user SET auto_pause_rules = %s WHERE id = %s",
                ["[]", row_id],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0087_alter_metadatabackfillstate_field"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0066_user_title_display_preference_and_more"),
    ]

    operations = [
        migrations.RunPython(
            _normalize_invalid_auto_pause_rules,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="tv_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="season_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="movie_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="anime_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="manga_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="game_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="book_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="boardgame_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="music_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="podcast_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="anime_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="boardgame_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="book_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comic_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="game_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="manga_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="movie_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="music_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="podcast_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="title",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="season_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tv_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tv_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="tv_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "season_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="season_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movie_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="movie_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "anime_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="anime_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "manga_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="manga_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "game_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="game_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "boardgame_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="boardgame_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "book_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="book_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "music_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="music_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "podcast_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="podcast_sort_valid",
            ),
        ),
    ]
