# Generated by Django 5.2.9 on 2026-02-17 15:42

from django.db import migrations, models


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0090_remove_themes_null"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0067_remove_user_tv_sort_valid_and_more"),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name="user",
            name="tv_sort_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="season_sort_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="movie_sort_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="anime_sort_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="manga_sort_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="game_sort_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="boardgame_sort_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="book_sort_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="music_sort_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="podcast_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="anime_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="boardgame_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="book_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comic_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="game_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="manga_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="movie_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="music_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="podcast_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="title",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="season_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tv_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("progress", "Progress"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tv_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="tv_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "season_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="season_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movie_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="movie_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "anime_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="anime_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "manga_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="manga_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "game_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="game_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "boardgame_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="boardgame_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "book_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="book_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "music_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="music_sort_valid",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "podcast_sort__in",
                        [
                            "score",
                            "title",
                            "progress",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="podcast_sort_valid",
            ),
        ),
    ]
