# Generated by Django 5.2.9 on 2026-02-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0091_fix_movie_progress"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0073_add_hide_zero_rating"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="list_detail_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="list_detail_sort",
            field=models.CharField(
                choices=[
                    ("date_added", "Date Added"),
                    ("custom", "Custom"),
                    ("title", "Title"),
                    ("media_type", "Media Type"),
                    ("rating", "Rating"),
                    ("progress", "Progress"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="date_added",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "list_detail_sort__in",
                        [
                            "date_added",
                            "custom",
                            "title",
                            "media_type",
                            "rating",
                            "progress",
                            "start_date",
                            "end_date",
                        ],
                    )
                ),
                name="list_detail_sort_valid",
            ),
        ),
    ]
