# Generated by Django 5.2.9 on 2026-03-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0078_user_authenticator_fields_and_recovery_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_discover_type",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
