# Generated by Django 5.2.9 on 2026-03-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0101_item_provider_game_lengths_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0081_remove_user_tv_sort_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="tv_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="season_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="movie_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="anime_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="manga_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="game_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="boardgame_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="book_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="music_sort_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="podcast_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="anime_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="boardgame_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="book_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comic_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="game_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="manga_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="movie_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="music_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="podcast_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="title",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="season_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tv_sort",
            field=models.CharField(
                choices=[
                    ("score", "Rating"),
                    ("title", "Title"),
                    ("author", "Author"),
                    ("progress", "Progress"),
                    ("runtime", "Runtime"),
                    ("time_to_beat", "Time to Beat"),
                    ("plays", "Plays"),
                    ("release_date", "Release Date"),
                    ("date_added", "Date Added"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("time_left", "Time Left"),
                ],
                default="score",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tv_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="tv_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "season_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="season_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movie_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="movie_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "anime_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="anime_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "manga_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="manga_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "game_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="game_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "boardgame_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="boardgame_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "book_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="book_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "music_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="music_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "podcast_sort__in",
                        [
                            "score",
                            "title",
                            "author",
                            "progress",
                            "runtime",
                            "time_to_beat",
                            "plays",
                            "release_date",
                            "date_added",
                            "start_date",
                            "end_date",
                            "time_left",
                        ],
                    )
                ),
                name="podcast_sort_valid",
            ),
        ),
    ]
