# Generated by Django 5.2.9 on 2026-03-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0102_itemproviderlink_metadataproviderpreference_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0082_remove_user_tv_sort_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anime_library_mode",
            field=models.CharField(
                choices=[
                    ("anime", "Anime Library"),
                    ("tv", "TV Library"),
                    ("both", "Both Libraries"),
                ],
                default="anime",
                help_text="Where grouped anime entries should surface in the UI.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="anime_metadata_source_default",
            field=models.CharField(
                choices=[
                    ("mal", "MyAnimeList"),
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                ],
                default="mal",
                help_text="Default metadata provider for Anime details and search tabs.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tv_metadata_source_default",
            field=models.CharField(
                choices=[("tmdb", "The Movie Database"), ("tvdb", "TheTVDB")],
                default="tmdb",
                help_text="Default metadata provider for TV details and search tabs.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tv_metadata_source_default__in", ["tmdb", "tvdb"])
                ),
                name="tv_metadata_source_default_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("anime_metadata_source_default__in", ["mal", "tmdb", "tvdb"])
                ),
                name="anime_metadata_source_default_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("anime_library_mode__in", ["anime", "tv", "both"])),
                name="anime_library_mode_valid",
            ),
        ),
    ]
